// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: proto/featureflags.proto

package featureflags

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FeatureValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*FeatureValue_BoolValue
	//	*FeatureValue_StringValue
	//	*FeatureValue_IntValue
	//	*FeatureValue_JsonValue
	Value         isFeatureValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeatureValue) Reset() {
	*x = FeatureValue{}
	mi := &file_proto_featureflags_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeatureValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureValue) ProtoMessage() {}

func (x *FeatureValue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_featureflags_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureValue.ProtoReflect.Descriptor instead.
func (*FeatureValue) Descriptor() ([]byte, []int) {
	return file_proto_featureflags_proto_rawDescGZIP(), []int{0}
}

func (x *FeatureValue) GetValue() isFeatureValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *FeatureValue) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*FeatureValue_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *FeatureValue) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*FeatureValue_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *FeatureValue) GetIntValue() int32 {
	if x != nil {
		if x, ok := x.Value.(*FeatureValue_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *FeatureValue) GetJsonValue() string {
	if x != nil {
		if x, ok := x.Value.(*FeatureValue_JsonValue); ok {
			return x.JsonValue
		}
	}
	return ""
}

type isFeatureValue_Value interface {
	isFeatureValue_Value()
}

type FeatureValue_BoolValue struct {
	BoolValue bool `protobuf:"varint,1,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type FeatureValue_StringValue struct {
	StringValue string `protobuf:"bytes,2,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type FeatureValue_IntValue struct {
	IntValue int32 `protobuf:"varint,3,opt,name=int_value,json=intValue,proto3,oneof"`
}

type FeatureValue_JsonValue struct {
	JsonValue string `protobuf:"bytes,4,opt,name=json_value,json=jsonValue,proto3,oneof"`
}

func (*FeatureValue_BoolValue) isFeatureValue_Value() {}

func (*FeatureValue_StringValue) isFeatureValue_Value() {}

func (*FeatureValue_IntValue) isFeatureValue_Value() {}

func (*FeatureValue_JsonValue) isFeatureValue_Value() {}

type FeatureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FeatureKey    string                 `protobuf:"bytes,1,opt,name=feature_key,json=featureKey,proto3" json:"feature_key,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	App           string                 `protobuf:"bytes,3,opt,name=app,proto3" json:"app,omitempty"`
	Env           string                 `protobuf:"bytes,4,opt,name=env,proto3" json:"env,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeatureRequest) Reset() {
	*x = FeatureRequest{}
	mi := &file_proto_featureflags_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeatureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureRequest) ProtoMessage() {}

func (x *FeatureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_featureflags_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureRequest.ProtoReflect.Descriptor instead.
func (*FeatureRequest) Descriptor() ([]byte, []int) {
	return file_proto_featureflags_proto_rawDescGZIP(), []int{1}
}

func (x *FeatureRequest) GetFeatureKey() string {
	if x != nil {
		return x.FeatureKey
	}
	return ""
}

func (x *FeatureRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FeatureRequest) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *FeatureRequest) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

type FeatureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *FeatureValue          `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeatureResponse) Reset() {
	*x = FeatureResponse{}
	mi := &file_proto_featureflags_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeatureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureResponse) ProtoMessage() {}

func (x *FeatureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_featureflags_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureResponse.ProtoReflect.Descriptor instead.
func (*FeatureResponse) Descriptor() ([]byte, []int) {
	return file_proto_featureflags_proto_rawDescGZIP(), []int{2}
}

func (x *FeatureResponse) GetValue() *FeatureValue {
	if x != nil {
		return x.Value
	}
	return nil
}

type FeatureConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FeatureKey    string                 `protobuf:"bytes,1,opt,name=feature_key,json=featureKey,proto3" json:"feature_key,omitempty"`
	Value         *FeatureValue          `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	App           string                 `protobuf:"bytes,3,opt,name=app,proto3" json:"app,omitempty"`
	Env           string                 `protobuf:"bytes,4,opt,name=env,proto3" json:"env,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeatureConfig) Reset() {
	*x = FeatureConfig{}
	mi := &file_proto_featureflags_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeatureConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureConfig) ProtoMessage() {}

func (x *FeatureConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_featureflags_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureConfig.ProtoReflect.Descriptor instead.
func (*FeatureConfig) Descriptor() ([]byte, []int) {
	return file_proto_featureflags_proto_rawDescGZIP(), []int{3}
}

func (x *FeatureConfig) GetFeatureKey() string {
	if x != nil {
		return x.FeatureKey
	}
	return ""
}

func (x *FeatureConfig) GetValue() *FeatureValue {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *FeatureConfig) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *FeatureConfig) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

type FeatureAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeatureAck) Reset() {
	*x = FeatureAck{}
	mi := &file_proto_featureflags_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeatureAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureAck) ProtoMessage() {}

func (x *FeatureAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_featureflags_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureAck.ProtoReflect.Descriptor instead.
func (*FeatureAck) Descriptor() ([]byte, []int) {
	return file_proto_featureflags_proto_rawDescGZIP(), []int{4}
}

func (x *FeatureAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_featureflags_proto protoreflect.FileDescriptor

const file_proto_featureflags_proto_rawDesc = "" +
	"\n" +
	"\x18proto/featureflags.proto\x12\ffeatureflags\"\x9d\x01\n" +
	"\fFeatureValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x01 \x01(\bH\x00R\tboolValue\x12#\n" +
	"\fstring_value\x18\x02 \x01(\tH\x00R\vstringValue\x12\x1d\n" +
	"\tint_value\x18\x03 \x01(\x05H\x00R\bintValue\x12\x1f\n" +
	"\n" +
	"json_value\x18\x04 \x01(\tH\x00R\tjsonValueB\a\n" +
	"\x05value\"n\n" +
	"\x0eFeatureRequest\x12\x1f\n" +
	"\vfeature_key\x18\x01 \x01(\tR\n" +
	"featureKey\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x10\n" +
	"\x03app\x18\x03 \x01(\tR\x03app\x12\x10\n" +
	"\x03env\x18\x04 \x01(\tR\x03env\"C\n" +
	"\x0fFeatureResponse\x120\n" +
	"\x05value\x18\x01 \x01(\v2\x1a.featureflags.FeatureValueR\x05value\"\x86\x01\n" +
	"\rFeatureConfig\x12\x1f\n" +
	"\vfeature_key\x18\x01 \x01(\tR\n" +
	"featureKey\x120\n" +
	"\x05value\x18\x02 \x01(\v2\x1a.featureflags.FeatureValueR\x05value\x12\x10\n" +
	"\x03app\x18\x03 \x01(\tR\x03app\x12\x10\n" +
	"\x03env\x18\x04 \x01(\tR\x03env\"&\n" +
	"\n" +
	"FeatureAck\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xed\x01\n" +
	"\fFeatureFlags\x12I\n" +
	"\n" +
	"GetFeature\x12\x1c.featureflags.FeatureRequest\x1a\x1d.featureflags.FeatureResponse\x12C\n" +
	"\n" +
	"SetFeature\x12\x1b.featureflags.FeatureConfig\x1a\x18.featureflags.FeatureAck\x12M\n" +
	"\fWatchFeature\x12\x1c.featureflags.FeatureRequest\x1a\x1d.featureflags.FeatureResponse0\x01B;Z9github.com/frandepy2/featureflags-grpc/proto;featureflagsb\x06proto3"

var (
	file_proto_featureflags_proto_rawDescOnce sync.Once
	file_proto_featureflags_proto_rawDescData []byte
)

func file_proto_featureflags_proto_rawDescGZIP() []byte {
	file_proto_featureflags_proto_rawDescOnce.Do(func() {
		file_proto_featureflags_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_featureflags_proto_rawDesc), len(file_proto_featureflags_proto_rawDesc)))
	})
	return file_proto_featureflags_proto_rawDescData
}

var file_proto_featureflags_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_featureflags_proto_goTypes = []any{
	(*FeatureValue)(nil),    // 0: featureflags.FeatureValue
	(*FeatureRequest)(nil),  // 1: featureflags.FeatureRequest
	(*FeatureResponse)(nil), // 2: featureflags.FeatureResponse
	(*FeatureConfig)(nil),   // 3: featureflags.FeatureConfig
	(*FeatureAck)(nil),      // 4: featureflags.FeatureAck
}
var file_proto_featureflags_proto_depIdxs = []int32{
	0, // 0: featureflags.FeatureResponse.value:type_name -> featureflags.FeatureValue
	0, // 1: featureflags.FeatureConfig.value:type_name -> featureflags.FeatureValue
	1, // 2: featureflags.FeatureFlags.GetFeature:input_type -> featureflags.FeatureRequest
	3, // 3: featureflags.FeatureFlags.SetFeature:input_type -> featureflags.FeatureConfig
	1, // 4: featureflags.FeatureFlags.WatchFeature:input_type -> featureflags.FeatureRequest
	2, // 5: featureflags.FeatureFlags.GetFeature:output_type -> featureflags.FeatureResponse
	4, // 6: featureflags.FeatureFlags.SetFeature:output_type -> featureflags.FeatureAck
	2, // 7: featureflags.FeatureFlags.WatchFeature:output_type -> featureflags.FeatureResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_featureflags_proto_init() }
func file_proto_featureflags_proto_init() {
	if File_proto_featureflags_proto != nil {
		return
	}
	file_proto_featureflags_proto_msgTypes[0].OneofWrappers = []any{
		(*FeatureValue_BoolValue)(nil),
		(*FeatureValue_StringValue)(nil),
		(*FeatureValue_IntValue)(nil),
		(*FeatureValue_JsonValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_featureflags_proto_rawDesc), len(file_proto_featureflags_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_featureflags_proto_goTypes,
		DependencyIndexes: file_proto_featureflags_proto_depIdxs,
		MessageInfos:      file_proto_featureflags_proto_msgTypes,
	}.Build()
	File_proto_featureflags_proto = out.File
	file_proto_featureflags_proto_goTypes = nil
	file_proto_featureflags_proto_depIdxs = nil
}
